config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shifts
  root 'shifts#index'
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :shift_times, only: [:show, :edit, :update, :destroy]

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :user
  belongs_to :shifttime

end

app/models/shift.rb
class Shift < ActiveRecord::Base
  belongs_to :user
  belongs_to :shift_time

end

app/models/shift_time.rb
class ShiftTime < ActiveRecord::Base
  has_many :shifts, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :shifts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/shift_times_controller.rb
class ShiftTimesController < ApplicationController

  def show
    @shift = Shift.find(params[:id])
    @date = params[:date]
    @shift_time = ShiftTime.find(params[:id])
    @user_ids = @shift_time.shifts.pluck(:user_id)
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController

  def index
    @shifts = Shift.all.includes(:user, :shift_time)
  end

  def new
    @new_shift = Shift.new
    @date = params[:date]
    date = "#{@date}\s00:00:00"
    @shifts = Shift.where(start_time: date)
    @shift_times = ShiftTime.all.map{|st| ["#{st.start_time}" + "-" + "#{st.end_time}", st.id]}
  end

  def create
    shift = params.require(:shift).permit(:start_time, :shift_time_id).merge(user_id: current_user.id, name: current_user.name)
    Shift.create(shift)
  end

  def show
    @shift = Shift.find(params[:id])
    @shift_time = @shift.shift_time
  end

  def edit
    @shift = Shift.find(params[:id])
    @shift_times = ShiftTime.all.map{|st| ["#{st.start_time}" + "-" + "#{st.end_time}", st.id]}
  end

  def update
    shift = Shift.find(params[:id])
    if shift.user_id == current_user.id
    shift.update(update_params)
    end
  end

  def destroy
    shift = Shift.find(params[:id])
    if shift.user_id == current_user.id
    shift.destroy
  end

end


  private

   def shift_params
    params.permit(:name, :start_time, :shift_time_id)
   end

   def update_params
    params.require(:shift).permit(:shift_time_id)
   end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @date = User.find(params[:id]).shifts.shift.start_end_time
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shift_times_helper.rb
module ShiftTimesHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1" />
    <title>悦子シフト管理アプリ</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </head>

  <body>
  <div id="container">
    <header id="header">
      <div class="header__bar row">
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.name %>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: "btn btn-default navbar-btn" %>
            </span>
          </div>
        <% else %>
          <!-- <div class="grid-6"> -->
        <% end %>
      </div>
    </header>

    <%= yield %>

  </div>
  </body>

  <footer>
    <p>
      Copyright 悦子 2017.
    </p>
  </footer>

</html>

app/views/shift_times/show.html.erb
<%= @date %>
<%= "#{@shift_time.start_time}-#{@shift_time.end_time}" %>
<% if @user_ids.include?(current_user.id) %>
<p><%= link_to "このシフトを変更する", edit_shift_path %></p>
<p><%= link_to "このシフトを削除する", shift_path, method: :delete %></p>
<% end %>

app/views/shifts/_form.html.erb
<%= form_for(@shift) do |f| %>
  <% if @shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
      <% @shift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shifts/create.html.erb
<h2>シフトを登録しました。</h2>

<%= link_to "カレンダーへ戻る", root_path %>

app/views/shifts/destroy.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>シフトの削除が完了しました。</h3>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>

app/views/shifts/edit.html.erb
<h2>シフトの変更・削除</h2>

<%= form_for @shift do |f| %>
  <%= f.label :"希望するシフトを選択する" %><br>
  <%= f.select :shift_time_id, @shift_times %>
  <%= f.submit "変更する" %>
<% end %>

app/views/shifts/index.html.erb
<h2>シフトを確認・登録</h2>

<div class='calender_wrapper'>
  <%= month_calendar events: @shifts do |date, shifts| %>
    <%= link_to new_shift_path(date: date), class: "date_link" do %>
      <p><%= date.strftime("%d") %></p>

      <% shifts.each do |shift| %>
        <% if shift.user == current_user %>
          <div class='myshift'>
            <%= shift.user.name %>
          </div>
        <% else %>
          <div>
            <%= shift.user.name %>
          </div>
        <% end %>

        <!-- <p><%= "#{shift.shift_time.start_time}-#{shift.shift_time.end_time}" %></p> -->

        <%#= link_to "#{shift.shift_time.start_time}-#{shift.shift_time.end_time}", shift_path(shift), id: "#{shift.shift_time_id}", date: "#{shift.shift_time.start_time}-#{shift.shift_time.end_time}" %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/shifts/new.html.erb
<div class="new_reg_container">
  <h3>シフトを新規登録</h3>
  <div class="contents row">
    <div class="container">
     <%= form_for @new_shift do |f| %>
      <%= f.label :"日付" %><br>
      <%= f.text_field :start_time, value: @date %><br><br>
      <%= f.label :"シフト時間枠" %><br>
      <%= f.select :shift_time_id, @shift_times %><br><br>
      <input type="submit" value="シフトを登録する">
     <% end %>
    </div>
  </div>
  <br><br>
  <h3>シフト一覧</h3>
  <ul>
    <% @shifts. each do |shift| %>
    <li>
      <%= shift.name %>
      <%= link_to "#{shift.shift_time.start_time}-#{shift.shift_time.end_time}", shift_path(shift), id: "#{shift.shift_time_id}", date: "#{shift.shift_time.start_time}-#{shift.shift_time.end_time}" %>
      <% end %>
    </li>
  </ul>
</div>

app/views/shifts/show.html.erb
<h2>シフトを変更・削除</h2>
<%= "#{@shift_time.start_time}-#{@shift_time.end_time}" %>
<% if @shift.user_id == current_user.id %>

<p><%= link_to "このシフトを変更する", edit_shift_path %></p>
<p><%= link_to "このシフトを削除する", shift_path, method: :delete %></p>
<% end %>

app/views/shifts/update.html.erb
<h1>変更を完了しました。</h1>

<%= link_to "ホームへ戻る", root_path %>

app/views/users/show.html.erb
<%= @date %>
<%= link_to "このシフトを変更する", edit_user_path %>
<%= link_to "このシフトを削除する", user_path, method: :delete %>

app/views/users/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>シフトの変更が完了しました。</h3>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>